[package]
name = "spitfire"
version = "0.1.0"
authors = ["Markus Eriksson <markus.eriksson.88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
